From: Timo RÃ¶hling <roehling@debian.org>
Bug: 1072057
Forwarded: not needed, alreay fixed upstream

diff --git a/pytest_asyncio/plugin.py b/pytest_asyncio/plugin.py
index 403d814..b29b755 100644
--- a/pytest_asyncio/plugin.py
+++ b/pytest_asyncio/plugin.py
@@ -272,9 +272,8 @@ def _wrap_asyncgen_fixture(fixturedef: FixtureDef) -> None:
     def _asyncgen_fixture_wrapper(
         event_loop: asyncio.AbstractEventLoop, request: SubRequest, **kwargs: Any
     ):
-        func = _perhaps_rebind_fixture_func(
-            fixture, request.instance, fixturedef.unittest
-        )
+        unittest = False if pytest.version_tuple >= (8, 2) else fixturedef.unittest
+        func = _perhaps_rebind_fixture_func(fixture, request.instance, unittest)
         gen_obj = func(**_add_kwargs(func, kwargs, event_loop, request))
 
         async def setup():
@@ -310,9 +309,8 @@ def _wrap_async_fixture(fixturedef: FixtureDef) -> None:
     def _async_fixture_wrapper(
         event_loop: asyncio.AbstractEventLoop, request: SubRequest, **kwargs: Any
     ):
-        func = _perhaps_rebind_fixture_func(
-            fixture, request.instance, fixturedef.unittest
-        )
+        unittest = False if pytest.version_tuple >= (8, 2) else fixturedef.unittest
+        func = _perhaps_rebind_fixture_func(fixture, request.instance, unittest)
 
         async def setup():
             res = await func(**_add_kwargs(func, kwargs, event_loop, request))
